# Generated by Django 4.2.23 on 2025-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='responder_content',
            field=models.TextField(blank=True),
        ),
    ]
